### ISSUE TITLE
Fall 2022 roadmap

### ISSUE THREAD

**Issue by lkatalin** [lkatalin/internship-roadmaps#1]
## Keylime 
For more, see [Keylime Rust agent roadmap](https://github.com/keylime/rust-keylime/issues/392)
- [ ] Add unit tests to the Rust Keylime agent to improve `cargo tarpaulin` coverage to 85% for all code paths
- [ ] Fix vulnerabilities found by https://deps.rs/repo/github/keylime/rust-keylime
- [ ] Bring in [keylime/keylime tests](https://github.com/keylime/keylime/blob/master/.ci/run_local.sh) to Rust agent CI to test on each new Rust agent PR that components still work together
- [ ] Try AWS's UEFI-supported AMIs to see if they are easier to bring up
- [ ] Update `keylime/keylime` documentation to refer to the Rust agent.
- [ ] Audit `README.md` files in repos under the [Keylime umbrella](https://github.com/keylime/) and update to fix any outdated information or discrepancies.
- [ ] Update AWS automation in `keylime-cloud-environments` based on [addressed issue](https://github.com/ansible-collections/amazon.aws/issues/944)

## Sigstore
- [ ] Take any open issues from the [`sigstore-rs` repo](https://github.com/sigstore/sigstore-rs/issues) and create PRs for them
- [ ] Familiarization
   - [ ] Stand up Rekor server and push / pull an artifact
   - [ ] Try out cosign to sign an artifact and verify the signature
- [ ] Find 5+ open source projects that could benefit from using the `sigstore-rs` library to secure their dependencies
   - [ ] Contact these projects with a proposal or POC using `sigstore-rs` to see if they are interested

## Container-based file integrity
- [ ] See [sec team issue](https://github.com/redhat-et/security-team/issues/84)
- [ ] See current WIP [repo](https://github.com/dave-tucker/syscall-digest)
